name: gbfs-ci
on:
  push:
    branches:
      - 'main'

jobs:
  deploy-minikube:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: gerrarde/gbfs
      - name: Start minikube
        uses: medyagh/setup-minikube@latest
        id: minikube
        with:
          cache: false
          addons: helm-tiller
      - name: Deploy to minikube
        run: |
          kubectl create ns monitoring
          kubectl run nginx --image=nginx -n=monitoring
          helm install -f grafana/values-production.yaml grafana grafana -n=monitoring
          kubectl wait --for=condition=ready pod -l run=nginx -n=monitoring
          kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=grafana -n=monitoring
      - name: List service URLs
        run: |
          minikube service list
      - name: Test service
        run: |
          echo -n "------------------calling the service------------------"
          kubectl exec -it pod/nginx -n=monitoring -- curl grafana.monitoring.svc.cluster.local
