name: gbfs-ci
on:
  push:
    branches:
      - 'main'

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: gerrarde/gbfs
      - name: Start minikube
        uses: medyagh/setup-minikube@latest
        id: minikube
        with:
          cache: false
          addons: helm-tiller
      - name: Deploy to minikube
        run: |
          kubectl create ns monitoring
          helm install -f grafana/values-production.yaml grafana grafana -n=monitoring
          kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=grafana -n=monitoring
      - name: Test service URLs
        run: |
          minikube service list
          minikube service grafana --url -n=monitoring
          echo -n "------------------opening the service------------------"
          curl $(minikube service grafana --url -n=monitoring)/version
