name: gbfs-ci
on:
  push:
    branches:
      - 'main'

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: gerrarde/gbfs
      - name: Start minikube
        uses: medyagh/setup-minikube@latest
        id: minikube
        with:
          cache: false
          addons: helm-tiller
      - name: Deploy to minikube
        run: |
          kubectl create ns monitoring
          helm install -f grafana/values-production.yaml grafana grafana -n=monitoring
          kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=grafana -n=monitoring
      - name: List service URLs
        run: |
          minikube service list
      - name: Expose service
        run: |
          export POD_NAME=$(kubectl get pods --namespace monitoring -l "app.kubernetes.io/name=grafana,app.kubernetes.io/instance=grafana" -o jsonpath="{.items[0].metadata.name}")
          kubectl --namespace monitoring port-forward $POD_NAME 3000
      - name: Call service URL
        run: |
          curl http://localhost:3000
